services:
  db:
    image: pgvector/pgvector:pg16
    
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d flightops"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  retrieval-svc:
    build:
      context: ..
      dockerfile: services/retrieval-svc/Dockerfile
    
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMBEDDINGS_MODEL=${EMBEDDINGS_MODEL}
    depends_on:
      db:
        condition: service_healthy
    ports: ["8081:8081"]

  comms-svc:
    build:
      context: ..
      dockerfile: services/comms-svc/Dockerfile
    
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHAT_MODEL=${CHAT_MODEL}
    ports: ["8083:8083"]

  agent-svc:
    build:
      context: ..
      dockerfile: services/agent-svc/Dockerfile
    
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - RETRIEVAL_URL=${RETRIEVAL_URL}
      - COMMS_URL=${COMMS_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHAT_MODEL=${CHAT_MODEL}
      - ALLOW_UNGROUNDED_ANSWERS=${ALLOW_UNGROUNDED_ANSWERS}
    depends_on:
      retrieval-svc:
        condition: service_started
      comms-svc:
        condition: service_started
    ports: ["8082:8082"]

  ingest-svc:
    build:
      context: ..
      dockerfile: services/ingest-svc/Dockerfile
    
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - EMBEDDINGS_MODEL=${EMBEDDINGS_MODEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    ports: ["8084:8084"]

  customer-chat-svc:
    build:
      context: ..
      dockerfile: services/customer-chat-svc/Dockerfile
    
    environment:
      - COMMS_URL=${COMMS_URL}
      - AGENT_URL=${AGENT_URL}
      - RETRIEVAL_URL=${RETRIEVAL_URL}
    depends_on:
      agent-svc:
        condition: service_started
      comms-svc:
        condition: service_started
      retrieval-svc:
        condition: service_started
    ports: ["8087:8087"]

  predictive-svc:
    build:
      context: ..
      dockerfile: services/predictive-svc/Dockerfile
    
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHAT_MODEL=${CHAT_MODEL}
    depends_on:
      db:
        condition: service_healthy
    ports: ["8085:8085"]

  crew-svc:
    build:
      context: ..
      dockerfile: services/crew-svc/Dockerfile
    
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHAT_MODEL=${CHAT_MODEL}
    depends_on:
      db:
        condition: service_healthy
    ports: ["8086:8086"]

  scalable-chatbot-svc:
    build:
      context: ..
      dockerfile: services/scalable-chatbot-svc/Dockerfile
    
    environment:
      - REDIS_URL=${REDIS_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHAT_MODEL=${CHAT_MODEL}
      - RETRIEVAL_URL=${RETRIEVAL_URL}
      - AGENT_URL=${AGENT_URL}
      - COMMS_URL=${COMMS_URL}
      - DEBUGPY=${DEBUGPY}
    depends_on:
      redis:
        condition: service_started
      retrieval-svc:
        condition: service_started
      agent-svc:
        condition: service_started
      comms-svc:
        condition: service_started
    ports: ["8088:8088", "5678:5678"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  gateway-api:
    build:
      context: ..
      dockerfile: services/gateway-api/Dockerfile
    
    environment:
      - AGENT_URL=${AGENT_URL}
      - RETRIEVAL_URL=${RETRIEVAL_URL}
      - COMMS_URL=${COMMS_URL}
      - INGEST_URL=${INGEST_URL}
      - CUSTOMER_CHAT_URL=${CUSTOMER_CHAT_URL}
      - PREDICTIVE_URL=${PREDICTIVE_URL}
      - CREW_URL=${CREW_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMBEDDINGS_MODEL=${EMBEDDINGS_MODEL}
    depends_on:
      agent-svc:
        condition: service_started
      retrieval-svc:
        condition: service_started
      comms-svc:
        condition: service_started
      ingest-svc:
        condition: service_started
      customer-chat-svc:
        condition: service_started
      predictive-svc:
        condition: service_started
      crew-svc:
        condition: service_started
    ports: ["8080:8080"]

  web:
    build:
      context: ..
      dockerfile: ui/web/Dockerfile
    
    environment:
      - NEXT_PUBLIC_GATEWAY_URL=${NEXT_PUBLIC_GATEWAY_URL}
    depends_on:
      gateway-api:
        condition: service_started
    ports: ["3000:3000"]

  stack-ready:
    image: alpine:3.19
    depends_on:
      web:
        condition: service_started
      gateway-api:
        condition: service_started
    command: ["/bin/sh", "-c", "echo 'FlightOps stack is ready — visit http://localhost:3000'" ]
    restart: "no"

volumes:
  dbdata:
